service: serverless-nodejs-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DEBUG: ${env:DEBUG , 0}
    DATABASE_URL: ${env:DATABASE_URL, "fall back value"}
  iam:
    role:
      name: serverless-ssm-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:GetParametersByPath"
            - "ssm:GetParametersHistory"
            - "ssm:DescribeParameters"

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DATABASE_URL
